### ISSUE TITLE
bounce wont compile

### ISSUE THREAD

**Issue by DenuxPlays** [bounce-rs/bounce#45]
Cargo.toml
```toml
[dependencies]
bounce = { git = "https://github.com/bounce-rs/bounce", features = ["helmet"] }
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
log = "0.4.17"
console_log = { version = "0.2.0", features = ["color"] }
wasm-bindgen = "0.2.80"
yew-router = { git = "https://github.com/yewstack/yew" }
gloo = { version = "0.8.0", features = ["futures"] }
web-sys= "0.3.57"
```

Error:
```
error[E0004]: non-exhaustive patterns: `&VNode::VRaw(_)` not covered
   |
23 |     match tag {
   |           ^^^ pattern `&VNode::VRaw(_)` not covered
   |
note: `VNode` defined here
   |
16 | pub enum VNode {
   | --------------
...
34 |     VRaw(VRaw),
   |     ^^^^ not covered
   = note: the matched value is of type `&VNode`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
   |
38 ~         VNode::VSuspense(_) => throw_str("expected text content, found suspense."),
39 ~         &VNode::VRaw(_) => todo!(),
   |

error[E0004]: non-exhaustive patterns: `&VNode::VRaw(_)` not covered
   |
57 |     match node {
   |           ^^^^ pattern `&VNode::VRaw(_)` not covered
   |
note: `VNode` defined here
   |
16 | pub enum VNode {
   | --------------
...
   |

```

i dont know why, what or anything...
it doesnt work... idk
